name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Build the app
      run: npm run build

    - name: Save build output
      run: zip -r output.zip .

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: build-output
        path: output.zip
